spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    user: ${FLYWAY_USERNAME}
    password: ${FLYWAY_PASSWORD}
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          writetimeout: 20000
          connectiontimeout: 20000
          timeout: 20000

application:
  jwt:
    secret-encryption-key: ${JWT_SECRET_ENCRYPTION_KEY}
    access-token:
      expiration-date: 86400000 # 1 day
    refresh-token:
      expiration-date: 604800000 # 7 days

  security:
    service:
      encryption:
        algorithm: AES
        aes-key: ${ENCRYPTION_AES_KEY}
    root:
      username: ${APP_ROOT_USERNAME}
      password: ${APP_ROOT_PASSWORD}
      uniqueName: ${APP_ROOT_UNIQUE_NAME}
      firstname: ${APP_ROOT_FIRST_NAME}
      lastname: ${APP_ROOT_LAST_NAME}
    admin:
      username: ${APP_ADMIN_USERNAME}
      password: ${APP_ADMIN_PASSWORD}
      uniqueName: ${APP_ADMIN_UNIQUE_NAME}
      firstname: ${APP_ADMIN_FIRST_NAME}
      lastname: ${APP_ADMIN_LAST_NAME}

  email:
    from: ${FROM_EMAIL}

  user:
    account:
      activation-code:
        expiration-time: 900000 # 15 min

  cors:
    origins:
      url: ${CORS_ORIGINS_URL}
