spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true

application:
  jwt:
    access-token:
      expiration-date: 86400000 # 1 day
    refresh-token:
      expiration-date: 604800000 # 7 days

  security:
    service:
      encryption:
        algorithm: AES
