package com.app.messenger.websocket.repository.model;

public enum NotificationType {
    NEW_SUBSCRIBER_NOTIFICATION,
    USER_STATUS_CHANGED,
    NEW_CHAT_NOTIFICATION,
    CHAT_DELETED_NOTIFICATION,
    CHAT_MEMBER_ROLE_CHANGED_NOTIFICATION,
    NEW_MESSAGE_NOTIFICATION,
    MESSAGE_DELETED_NOTIFICATION,
    MESSAGE_UPDATED_NOTIFICATION
}
